session_scheduler/urls.py
from . import views
from django.urls import path
from session_scheduler.views import edit_session, delete_session

urlpatterns = [
    path('', views.BeachList.as_view(), name='home'),
    path('<slug:slug>/', views.BeachSessions.as_view(), name='beach_sessions'),
    path('edit/<item_id>', edit_session, name='edit'),
    path('delete/<item_id>', delete_session, name='delete'),
]

surfclub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('session_scheduler.urls'), name='session_scheduler.urls'),
    path('accounts/', include('allauth.urls')),
    ]

session_scheduler/models.py
from django.db import models

from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


class Beach(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    beach_image = CloudinaryField('image', default='placeholder')
    facing = models.CharField(max_length=50)
    latitude = models.CharField(max_length=50)
    longitude = models.CharField(max_length=50)
    notes = models.TextField()

    def __str__(self):
        return self.name


class Session(models.Model):
    TIME_CHOICES = [
        ('06', '06.00'),
        ('07', '07.00'),
        ('08', '08.00'),
        ('09', '09.00'),
        ('10', '10.00'),
        ('11', '11.00'),
        ('12', '12.00'),
        ('13', '13.00'),
        ('14', '14.00'),
        ('15', '15.00'),
        ('16', '16.00'),
        ('17', '17.00'),
        ('18', '18.00'),
        ('19', '19.00'),
        ('20', '20.00'),
        ('21', '21.00'),
        ('22', '22.00'),
    ]

    beach = models.ForeignKey(Beach, on_delete=models.CASCADE,
                              related_name="sessions")
    time = models.CharField(
        max_length=2,
        choices=TIME_CHOICES)
    date = models.DateField(auto_now=False)
    surfer = models.ForeignKey(User, on_delete=models.CASCADE)

    # FIX THIS LATER
    # def __str__(self):
    #     return self.User

session_scheduler/forms.py
from .models import Session
from django import forms


class DateInput(forms.DateInput):
    input_type = "date"


class SessionForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = ('date', 'time',)
        widgets = {"date": DateInput()}

session_scheduler/views.py
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from .models import Beach, Session
from .forms import SessionForm


class BeachList(generic.ListView):
    model = Beach
    queryset = Beach.objects.order_by("name")
    template_name = "index.html"


today = datetime.datetime.now()
tomorrow = today + datetime.timedelta(days=1)
day_after_tomorrow = today + datetime.timedelta(days=2)


class BeachSessions(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Beach
        beach = get_object_or_404(queryset, slug=slug)
        sessions = beach.sessions.filter(
            date__gte=today, date__lte=day_after_tomorrow).order_by(
                "date", "time")
        return render(
            request,
            "beach_sessions.html",
            {
                "beach": beach,
                "sessions": sessions,
                "session_form": SessionForm(),
                "today": today,
                "tomorrow": tomorrow,
                "day_after_tomorrow": day_after_tomorrow,
            }
         )

    def post(self, request, slug, *args, **kwargs):
        queryset = Beach
        beach = get_object_or_404(queryset, slug=slug)
        sessions = beach.sessions.filter(
            date__gte=today, date__lte=day_after_tomorrow).order_by(
                "date", "time")

        session_form = SessionForm(data=request.POST)

        if session_form.is_valid():
            session_form.instance.surfer = request.user
            session = session_form.save(commit=False)
            session.beach = beach
            session.save()
        else:
            session_form = SessionForm()

        return render(
            request,
            "beach_sessions.html",
            {
                "beach": beach,
                "sessions": sessions,
                "session_form": SessionForm(),
                "today": today,
                "tomorrow": tomorrow,
                "day_after_tomorrow": day_after_tomorrow,
            }
         )


def edit_session(request, item_id):

    session = get_object_or_404(Session, id=item_id)
    beach = session.beach
    slug = beach.slug

    if request.method == "POST":
        session_form = SessionForm(request.POST, instance=session)
        if session_form.is_valid():
            session_form.instance.surfer = request.user
            session = session_form.save(commit=False)
            session.save()
            return redirect('beach_sessions', slug=slug)
    context = {
        'session_form': SessionForm(),
        'beach': beach
    }
    return render(request, "edit_session.html", context)


def delete_session(request, item_id):
    session = get_object_or_404(Session, id=item_id)
    beach = session.beach
    slug = beach.slug
    username = session.surfer
    time = session.time
    date = session.date
    if request.method == 'POST':
        session.delete()
        return redirect('beach_sessions', slug=slug)
    context = {
        'session': session,
        'username': username,
        'beach': beach,
        'time': time,
        'date': date,
    }
    return render(request, 'delete_session.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fresca&display=swap" rel="stylesheet">         
    <title>Belmullet Surf Club</title>
</head>
<body style="font-family: 'Fresca', san serif">
    <div class="container pl-2">
        <h1>
            <a class="nav-link-active" href="{% url 'home' %}" style="text-decoration: none">Belmullet Surf Club</a>
        </h1> 
        <nav >
        {% if user.is_authenticated %}
            <a class="nav-link " href="{% url 'account_logout' %}">Logout</a>
        {% else %}
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        {% endif %}
        </nav>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                <div class="alert {{message.tags}} alert-dismissible fade show" id="msg" role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% block content %}

    {% endblock %}
    {% block js %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/beach_sessions.html
{% extends 'base.html' %} {% block content %}

<div class="container pl-2">
    <div>
        <h3>{{ beach.name }} Beach</h3>
        <div class="row">
            <div class="col-10">
                <img src=" {{ beach.beach_image.url }}" alt="responsive image of beach in question" width="100%" height="auto" class="image-fluid">
            </div>
            <div class="col-2">
            </div>
        </div>
        <div>
            <div class="container pl-2">
                <div class="row">
                    <div class="col-4">
                        <strong>Facing: </strong>{{ beach.facing}}
                    </div>
                    <div class="col-6">
                        <strong>Coordinates: </strong>{{ beach.latitude }}, {{ beach.longitude }}
                    </div>
                    <div class="col-2">
                    </div>
                </div>
                <div class="row">
                    <div class="col-9">
                        <p>{{ beach.notes }}</p>
                    </div>
                    <div class="col-3">
                    </div>
                </div>
            </div>
            {% if user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                {{ session_form }}
                <button type="submit" class="btn btn-outline-info">+ add a session</button>
            </form>
            {% endif %}
        </div>
    </div>
        <h3>Upcoming sessions</h3>
        {% if user.is_authenticated %}
            {% regroup sessions by date as session_list %}
            {% for day, session_group in session_list %} 
                <strong>
                    {% if day|date:"F d, Y" == today|date:"F d, Y" %}
                        Today:
                    {% elif day|date:"F d, Y" == tomorrow|date:"F d, Y" %}
                        Tomorrow:
                    {% elif day|date:"F d, Y" == day_after_tomorrow|date:"F d, Y" %}
                        The day after tomorrow:
                    {% else %}
                    xxxxxx
                        
                    {% endif %}
                    {{ day }} 
                </strong>
                {% for session in session_group %}
                    
                <ul class="list-inline">
                    <li class="list-inline-item">{{ session.time }}.00</li>
                    <li class="list-inline-item">{{ session.surfer }}</li>
                    <li class="list-inline-item">{{ session.date }}</li>   
                    {% if user == session.surfer %}
                    
                    <li class="list-inline-item">
                        <button onClick="location.href='/edit/{{ session.id }}'" class="btn btn-outline-primary btn-sm">Edit this session</button>
                    </li>
                    <li class="list-inline-item">
                        <button onClick="location.href='/delete/{{ session.id }}'" class="btn btn-outline-secondary btn-sm">Delete this session</button>
                    </li>
                    {% endif %}
                </ul>      
                
                {% empty %}
                    <p>No sessions found for {{ day }}</p>
                {% endfor %}
            {% empty %}
                <p>No sessions found</p>
            {% endfor %}
        {% else %}
            <p>
                Sessions are only viewable to members of Belmullet Surfclub. If you are a member, 
                who does not yet have an account, you can contact Cillian to have one made for you.
            </p>
        {% endif %}
        
</div> 


{% endblock %}

{% block js %}
<script>
    today = new Date();
    let minDate = today.toISOString().substring(0, 10);
    document.getElementById("id_date").setAttribute("min", minDate); 
</script>
{% endblock %}

templates/delete_session.html
{% extends 'base.html' %} {% block content %}
<div class="container pl-2">
    <h2>Are you sure?</h2>
        <form method="post">
        {% csrf_token %}
            <p>{{ session.surfer }}, Are you sure you wish to delete your session on
            {{ beach.name }} Beach, at {{ time }}.00 on {{ date }}?</p>
            <button class="btn btn-outline-danger">I am sure</button>
        </form>
</div>
{% endblock %}

templates/edit_session.html
{% extends 'base.html' %} {% block content %}
<div class="container pl-2">
    <h2>Edit Sessions for {{ beach.name }} Beach</h2>
    <form method="post">
        {% csrf_token %}
        {{ session_form }}
        <button class="btn btn-outline-primary">Confirm edit</button>
    </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container pl-2">
    <div class="row">
        <div class="col-9">
            <p>
                Welcome to Belmullet Surf Club's session tracker site! Below you'll find listings with basic info 
                on all of our "club-approved" beaches. Once you sign in with the account made for you by the club, 
                you'll be able to view times when other surfers are heading out, as well as post sessions to let others 
                know when you'll be paddling out! Make sure to check the notes on each beach, we'll be keeping them 
                updated with changes to beaches, and reminders for club events!  
            </p>
        </div>
        <div class="col-3">
        </div>
    </div>
</div>    
<div class="container-fluid">
    {% for beach in beach_list %}
    <div class="container pl-2">
        <p class="h2">{{ beach.name }} 
            <button onClick="location.href='{% url 'beach_sessions' beach.slug %}'"class="btn btn-outline-primary btn-sm">
                View sessions
            </button>
        </p> 
    </div>
    <div class="container">
        <div class="row">
            <div class="col-10" max-height="50%" max-width="80%">
                <img src=" {{ beach.beach_image.url }}" alt="responsive image of beach in question" width="100%" height="auto" class="image-fluid">
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
    <div class="container pl-2">
        <div class="row">
            <div class="col-4">
                <strong>Facing: </strong>{{ beach.facing}}
            </div>
            <div class="col-6">
                <strong>Coordinates: </strong>{{ beach.latitude }}, {{ beach.longitude }}
            </div>
            <div class="col-2">
            </div>
        </div>
        <div class="row">
            <div class="col-9">
                <p>{{ beach.notes }}</p>
            </div>
            <div class="col-3">
            </div>
        </div>
        
    </div>
    
    {% endfor %}
</div> 


{% endblock %}